# Generated by Django 5.2.6 on 2025-09-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Plataforma')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site oficial')),
            ],
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='filmes',
            name='ano_lancamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de lançamento'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='filme',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='filmes',
            name='plataformas',
            field=models.ManyToManyField(related_name='filmes', to='streaming.plataformas'),
        ),
    ]
